project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - workshops/large-language-models.qmd
    - workshops/prompting.qmd
    - workshops/quarto-academic-writing.qmd
    - workshops/literature-research.qmd
    - workshops/git-github.qmd
    - general/scientific-writing.qmd
    - general/literature.qmd

website:
  title: "Seminar Preparation"
  repo-url: https://github.com/beyondsimulations/Research-Workshops
  repo-actions: [edit, source, issue]
  site-url: https://beyondsimulations.github.io/Research-Workshops
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/logo/midjourney-solar-mirror.png
    collapse-level: 1
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "***"
      - text: "AI Tools"
        href: workshops/large-language-models.qmd
      - text: "Prompting"
        href: workshops/prompting.qmd
      - text: "Quarto"
        href: workshops/quarto-academic-writing.qmd
      - text: "Literature"
        href: workshops/literature-research.qmd
      - text: "Git"
        href: workshops/git-github.qmd
      - text: "***"
      - text: "Writing Guide"
        href: general/scientific-writing.qmd
      - text: "Resources"
        href: general/literature.qmd

  page-footer:
    center: "Research Workshops, Tobias Vlćek</br>CC BY-NC-SA 4.0"
    right:
      - icon: github
        href: https://github.com/beyondsimulations/Research-Workshops
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme:
      - default
      - styles.scss
      - brand
    toc: true
    highlight-style: github
    callout-appearance: simple
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    include-in-header:
      - general/header.html

execute:
  freeze: auto

brand: _brand.yml
