---
title: "Literature and Resources"
subtitle: "Good books and resources to read"

html:
    theme: [default, ../styles.scss]
    code-copy: true
    code-link: true
    toc: true
    toc-location: right
---

This section provides a curated list of books and resources to enhance your understanding of Geographical Data Analysis and Large Language Models. Each recommendation includes a brief description to help you choose the most suitable resources for you.

# Geographical Data Analysis

## Books

- [Geospatial Data Science with Julia](https://juliaearth.github.io/geospatial-data-science-with-julia/02-geoviz.html): A book that is great for beginners and covers Geographical Data Analysis from the ground up with Julia.

## Resources

- [QGis](https://www.qgis.org/en/site/): A free and open-source GIS software that is very powerful and flexible.
- [Mapbox](https://www.mapbox.com/): A platform that provides tools for creating maps and geospatial data. It has a great documentation and very generous free tier.
- [OpenStreetMap](https://www.openstreetmap.org/): A free and open-source map of the world. It is very detailed and can be used for a a lot of purposes. Great for getting started with Geographical Data Analysis and getting data.

# Large Language Models

## Hosted LLMs

These are powerful LLMs hosted by companies, which you can access through APIs (Application Programming Interfaces). You typically pay for usage.

- [OpenAI (ChatGPT)](https://chatgpt.com): The creators of ChatGPT and GPT-4, offering a range of models.
- [Mistral](https://mistral.ai/): A European-based company offering competitive models.
- [Google (Gemini)](https://gemini.google.com/): Google's LLM, offering strong performance and integration with Google services.
- [Anthropic (Claude)](https://www.anthropic.com/claude): Known for its its ability to handle code effectively.

## Local LLMs

These tools can be used to run open-source LLMs that you can download and run on your own machine. This gives you more privacy and control, but requires more technical expertise and computational resources.

- [Ollama](https://ollama.com/): Free and open-source tool to run large language models locally, supports a wide range of models. Note, that the models are not as powerful as the hosted ones and that your computer needs to have a good GPU to run larger models. Smaller models with less than 8B parameters can also often be run on a CPU with enough available RAM. Great for privacy and if you don't want to pay for the hosted models.
- [Hugging Face](https://huggingface.co/): Hosts a wide range of large language models, including models fine-tuned for specific tasks by the community. Models can also be downloaded to Ollama and run locally, if your computer is powerful enough.

## Working with data

In addition to the hosted and local LLMs, there are also tools that allow you to work with LLMs in a browser to build RAG apps or custom chatbots.

- [NotebookLM](https://notebooklm.google/)**: Google's Gemini that can be fed with files, images and YouTube videos to generate text based on the content. Only works within a workspace of Google, you can't make it available to the public (yet).
- [Open Web UI](https://openwebui.com/)**: Open Web UI is a tool to run large language models locally (in conjuction with, for example, Ollama). It is a browser-based interface that allows you to interact with the models and build RAG apps.

# Data Science

## Books

- Wilke, C. (2019). Fundamentals of data visualization: A primer on making informative and compelling figures (First edition). O’Reilly Media.
    - A book that is highly recommended to understand the principles of data visualization and how to create effective visualizations.
    - [Link to the free book website](https://clauswilke.com/dataviz/)
- Thomas, D., & Hunt, A. (2019). The pragmatic programmer, 20th anniversary edition: Journey to mastery (Second edition). Addison-Wesley.
    - A fantasticbook to understand the principles of software development and how to create effective software.

## Resources

- [Quarto](https://quarto.org)
    - A static website generator that is very powerful and flexible. Used to create the slides and the website for the course.
- [Jupyter](https://jupyter.org)
    - A web application that allows you to create and share documents that contain code, equations, visualizations and text. It is very popular in the field of data science and academia and also part of Quarto.
- [Github](https://github.com)
    - The largest provider for git repositories owned by Microsoft. A lot of open source projects are hosted here and you can read the code. 
- [Daily Dose of Data Science](https://www.dailydoseofds.com)
    - A website and a newsletter with lots of easy-to-digest resources to improve your skills in Data Science.
    